---
version: "3.8"
services:
  node_0:
    build:
      context: ../..
      dockerfile: dockerfiles/ubuntu/Dockerfile
    volumes:
      - "/tmp:/tmp"
      - "./configs:/configs"
      - "./ssh:/local_ssh"
    command: "cluster.yaml node_0.yaml"
    networks:
      bobnet:
        ipv4_address: 192.168.17.10
    ports:
      - "8000:8000"
      - "7022:22"
    security_opt:
      - "seccomp:./profile.json"
    ulimits:
      memlock: 4194304
  node_1:
    build:
      context: ../..
      dockerfile: dockerfiles/ubuntu/Dockerfile
    volumes:
      - "/tmp:/tmp"
      - "./configs:/configs"
      - "./ssh:/local_ssh"
    command: "cluster.yaml node_1.yaml"
    networks:
      bobnet:
        ipv4_address: 192.168.17.11
    ports:
      - "8001:8000"
      - "7023:22"
    security_opt:
      - "seccomp:./profile.json"
    ulimits:
      memlock: 4194304
networks:
  bobnet:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.17.0/24
