[package]
name = "bob"
version = "2.0.0-alpha.3"
authors = [
    "Kirill Bushminkin <kb@qoollo.com>",
    "Pavel Iakushin <pyakushin@qoollo.com>",
]
edition = "2018"

[dependencies]

anyhow = "1.0.38"
async-trait = "0.1"
bitflags = "1.2.1"
bob-backend = { path = "../bob-backend" }
bob-common = { path = "../bob-common" }
bob-grpc = { path = "../bob-grpc" }
bytes = "1.0.1"
cfg-if = "1.0"
chrono = "0.4"
env_logger = "0.8"
futures = { version = "0.3.12", features = ["thread-pool"] }
http = "0.2.3"
humantime = "2.1.0"
hyper = "0.14.2"
#metrics = "0.12.1"
infer = "0.3.5"
lazy_static = "1.4.0"
log = "0.4"
metrics = { version = "0.16", features = ["std"] }
mockall = "0.9.0"
prost = "0.7.0"
ring = "0.16.19"
rocket = { version = "0.5.0-rc.1", features = ["json", "uuid"] }
serde = "1.0"
serde_derive = "1.0"
serde_yaml = "0.8"
stopwatch = "0.0.7"
termion = "1.5"
thiserror = "1.0"
tonic = { version = "0.4.0", features = ["prost"] }
tower = "0.4.3"
tower-service = "0.3.0"

[dependencies.pearl]
version = "=0.6.1"
# git = "https://github.com/qoollo/pearl"
# branch = "106-extend-version"

[dependencies.tokio]
version = "1.4"
features = ["full"]
# git = "https://github.com/qoollo/pearl"
# branch = "observer-force-shutdown-on-close"

[build-dependencies]
tonic-build = "0.4.0"
chrono = "0.4"
