[package]
name = "bob"
version = "1.6.1"
authors = ["Kirill Bushminkin <kb@qoollo.com>", "Pavel Iakushin <pyakushin@qoollo.com>"]
edition = "2018"

[dependencies]
bob-common = { version = "1.5.1-alpha.4", path = "../bob-common" }
bob-backend = { version = "1.5.1-alpha.4", path = "../bob-backend" }
bob-grpc = { version = "1.5.1-alpha.4", path = "../bob-grpc" }

anyhow = "1.0.38"
env_logger = "0.8"
http = "0.2.3"
futures = { version = "0.3.12", features = ["thread-pool"] }
serde = "1.0"
serde_derive = "1.0"
serde_yaml = "0.8"
log = "0.4"
bitflags = "1.2.1"
prost = "0.7.0"
bytes = "1.0.1"
stopwatch = "0.0.7"
hyper = "0.14.2"
humantime = "2.1.0"
chrono = "0.4"
mockall = "0.9.0"
cfg-if = "1.0"
tonic = { version = "0.4.0", features = ["prost"] }
tower = "0.4.3"
tower-service = "0.3.0"
rocket = "0.4.6"
rocket_contrib = "0.4.6"
async-trait = "0.1"
termion = "1.5"
ring = "0.16.19"
lazy_static = "1.4.0"
thiserror = "1.0"
metrics = { version = "0.12.1", features = ["std"] }
#metrics = "0.12.1"
infer = "0.3.5"

[dependencies.tokio]
version = "1.4"
features = ["full"]

[dependencies.pearl]
version = "=0.5.14"
# git = "https://github.com/qoollo/pearl"
# branch = "observer-force-shutdown-on-close"

[build-dependencies]
tonic-build = "0.4.0"
