# Count of nodes in cluster
nodes_count: 2
# Count of vdisks on each node
vdisks_count: 2
# Global logging level
logging_level: warn
# Optional: ssh pub key for password-less ssh
ssh_pub_key: ""
# Quorum of cluster
quorum: 2