[package]
name = "bob-access"
version = "2.0.0-alpha.3"
authors = ["Pavel Iakushin <pyakushin@qoollo.com>"]
edition = "2018"

[dependencies]
http = "0.2"
tower = "0.4"
tonic = "0.5"
log = "0.4"
serde = {version = "1.0", features = ["derive"] }
jsonwebtoken = "7.2"
serde_yaml = "0.8"
rocket = "0.5.0-rc.1"
futures = "0.3"