[package]
name = "bob-access"
version = "1.6.1"
authors = ["Pavel Iakushin <pyakushin@qoollo.com>"]
edition = "2018"

[dependencies]
tower = "*"
tonic = "*"
log = "*"
serde = { version="1.0", features=["derive"] }
serde_yaml = "0.8"
rocket = "0.4.6"
