[package]
name = "bob-access"
version = "2.0.0-alpha.2"
authors = ["Pavel Iakushin <pyakushin@qoollo.com>"]
edition = "2018"

[dependencies]
http = "0.2.4"
tower = "*"
tonic = "0.5.2"
log = "*"
serde = {version = "1.0", features = ["derive"] }
jsonwebtoken = "7"
serde_yaml = "0.8"
rocket = "0.4.6"
