[package]
name = "bob-access"
version = "2.1.0-alpha.6"
authors = ["Pavel Iakushin <pyakushin@qoollo.com>"]
edition = "2021"

[dependencies]
axum = "0.4"
bitflags = "1.3"
hex = "0.4.3"
http = "0.2"
sha2 = "0.10.2"
tower = "0.4"
tonic = "0.6"
log = "0.4"
serde = {version = "1.0", features = ["derive"] }
jsonwebtoken = "7.2"
serde_yaml = "0.8"
serde_json = "1.0"
futures = "0.3"