[package]
name = "bob-common"
version = "2.0.0-alpha.11"
authors = ["Kirill Bushminkin <kb@qoollo.com>", "Pavel Iakushin <pyakushin@qoollo.com>"]
edition = "2018"

[dependencies]
async-trait = "0.1"
bitflags = "1.3"
bob-grpc = { path = "../bob-grpc" }
bytes = "1.1"
cfg-if = "1.0"
chrono = "0.4"
futures = { version = "0.3", features = ["thread-pool"] }
http = "0.2"
humantime = "2.1.0"
hyper = { version = "0.14", default-features = false }
lazy_static = "1.4"
log = "0.4"
metrics = { version = "0.17", features = ["std"] }
metrics-exporter-prometheus = { version = "0.6", features = ["tokio-exporter"]}
metrics-util = "0.10"
mockall = "0.10"
prost = "0.9"
serde = { version = "1.0", features = ["rc"] }
serde_derive = "1.0"
serde_yaml = "0.8"
thiserror = "1.0"
tonic = { version = "0.6", features = ["prost"] }
tower = "0.4"
tower-service = "0.3"

[dependencies.tokio]
version = "1.14"
default-features = false
features = []

[features]
testing = []
