[package]
name = "bob-common"
version = "2.1.0-alpha.10"
authors = [
    "Kirill Bushminkin <kb@qoollo.com>",
    "Pavel Iakushin <pyakushin@qoollo.com>",
    "Nikita Menshov",
    "Ilia Kopylov",
    "Ivan Druzhitskiy",
    "Vladimir Stepanenko",
    "Pavel Perestoronin",
    "Konstantin Konnov",
    "Konstantin Bulany"
]
edition = "2021"

[dependencies]
anyhow = "1.0"
async-trait = "0.1"
base64 = "0.13.0"
bitflags = "1.3"
bob-access = { path = "../bob-access" }
bob-grpc = { path = "../bob-grpc" }
bytes = "1.2"
cfg-if = "1.0"
chrono = "0.4"
coarsetime = "0.1.21"
futures = { version = "0.3", features = ["thread-pool"] }
http = "0.2"
humantime = "2.1.0"
hyper = { version = "0.14", default-features = false }
lazy_static = "1.4"
log = "0.4"
metrics = { version = "0.17", features = ["std"] }
metrics-exporter-prometheus = { version = "0.6", features = ["tokio-exporter"]}
metrics-util = "0.10"
mockall = "0.11"
prost = "0.11"
serde = { version = "1.0", features = ["rc"] }
serde_derive = "1.0"
serde_yaml = "0.8"
thiserror = "1.0"
tonic = { version = "0.6", features = ["prost", "tls"] }
tower = "0.4"
tower-service = "0.3"
ubyte = { version = "0.10", features = ["serde"] }

[dependencies.tokio]
version = "1.21"
default-features = false
features = ["fs"]

[features]
default = []
testing = []
production = []
