[package]
name = "bob-common"
version = "2.0.0-alpha.2"
authors = ["Kirill Bushminkin <kb@qoollo.com>", "Pavel Iakushin <pyakushin@qoollo.com>"]
edition = "2018"

[dependencies]
async-trait = "0.1"
bitflags = "1.2.1"
bob-grpc = { path = "../bob-grpc" }
bytes = "1.0.1"
cfg-if = "1.0"
chrono = "0.4"
futures = { version = "0.3.12", features = ["thread-pool"] }

http = "0.2.3"
humantime = "2.1.0"
hyper = "0.14.2"
lazy_static = "1.4.0"
log = "0.4"
metrics = { version = "0.16", features = ["std"] }
metrics-exporter-prometheus = "0.5"
metrics-util = "0.8"
mockall = "0.9.0"
prost = "0.7.0"
serde = { version = "1.0", features = ["rc"] }
serde_derive = "1.0"
serde_yaml = "0.8"
thiserror = "1.0"
tonic = { version = "0.4.0", features = ["prost"] }
tower = "0.4.3"
tower-service = "0.3.0"
#metrics = "0.12.1"

[dependencies.tokio]
version = "1.4"
features = ["full"]

[build-dependencies]
tonic-build = "0.4.0"

