---
refresh_rate: 30 seconds
appenders:
  stdout:
    kind: console
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S):<20} {M:>20.30}:{L:>3} {h({l})}    {m}\n"
root:
  level: info
  appenders:
    - stdout
loggers:
  pearl:
    level: warn
    appenders:
      - stdout
    additive: false
  bob:
    level: info
    appenders:
      - stdout
    additive: false
