openapi: 3.0.0
info:
  title: "Bob Node API"
  description: Bob HTTP Rest API
  version: 0.0.0
paths:
  /status:
    get:
      summary: Returns information about self
      operationId: getStatus
      responses:
        '200':
          description: "A JSON with node info"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Node'
        default:
          $ref: '#/components/responses/DefaultError'
  /version:
    get:
      summary: Returns server version
      operationId: getVersion
      responses:
        '200':
          description: "Version string"
          content: 
            text/plain:
              schema:
                type: string
                example: 1.6.1-cb85dca16f40567b262c393abff15be01d4a2df5
  /nodes:
    get:
      summary: Returns a list of known nodes
      operationId: getNodes
      responses:
        '200':
          description: "A JSON array of nodes info and vdisks on them"
          content:
            application/json:
              schema:
                type: array
                items: 
                  $ref: '#/components/schemas/Node'
        default:
          $ref: '#/components/responses/DefaultError'
  /metadata/distrfunc:
    get:
      summary: Return information about key distribution function
      operationId: distributionFunction
      responses:
        '200':
          description: "Distribution function information"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DistrFunc'
  /vdisks:
    get:
      summary: Returns a list of vdisks
      operationId: getVDisks
      responses:
        '200':
          description: "A JSON array of vdisks info"
          content:
            application/json:
              schema:
                type: array
                items: 
                  $ref: '#/components/schemas/VDisk'
        default:
          $ref: '#/components/responses/DefaultError'
  /vdisks/{VDiskId}:
    get:
      summary: Returns a vdisk info by ID
      operationId: getVDisk
      parameters:
        - $ref: '#/components/parameters/VDiskIdParam'
      responses:
        '200':
          description: "A JSON with vdisk info"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VDisk'
        default:
          $ref: '#/components/responses/DefaultError'
  /vdisks/{VDiskId}/records/count:
    get:
      summary: Returns count of records of this on node
      operationId: getRecords
      parameters:
        - $ref: '#/components/parameters/VDiskIdParam'
      responses:
        '200':
          description: "Records count"
          content:
            application/json:
              schema:
                type: integer
        default:
          $ref: '#/components/responses/DefaultError'
  /vdisks/{VDiskId}/partitions:
    get:
      summary: Returns a list of partitions
      operationId: getPartitions
      parameters:
        - $ref: '#/components/parameters/VDiskIdParam'
      responses:
        '200':
          description: "Node info and JSON array with partitions info"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VDiskPartitions'
        default:
          $ref: '#/components/responses/DefaultError'
  /vdisks/{VDiskId}/partitions/{partitionId}:
    get:
      summary: Returns a partition info by ID
      operationId: getPartition
      parameters: 
        - $ref: '#/components/parameters/VDiskIdParam'
        - name: partitionId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: "A JSON with partition info"
          content:
            application/json:
              schema:
                type: string
        default:
          $ref: '#/components/responses/DefaultError'
  /vdisks/{VDiskId}/partitions/by_timestamp/{timestamp}:
    delete:
      summary: Delete partitions by timestamp
      parameters:
        - $ref: '#/components/parameters/VDiskIdParam'
        - name: timestamp
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: string
        default:
          $ref: '#/components/responses/DefaultError'
  /vdisks/{VDiskId}/partitions/by_timestamp/{timestamp}/{action}:
    put:
      summary: Attach/Detach a partition by timestamp
      parameters: 
        - $ref: '#/components/parameters/VDiskIdParam'
        - name: timestamp
          in: path
          required: true
          schema:
            type: string
        - in: path
          name: action
          schema:
            type: string
            enum: 
              - attach
              - detach
          required: true
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: string
        default:
          $ref: '#/components/responses/DefaultError'
  /disks/list:
    get:
      summary: Returns the list of disks with their states
      operationID: getDisks
      responses:
        '200':
          description: "A JSON array with disks and their states"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DiskState'
        default:
          $ref: '#/components/responses/DefaultError'
  /disks/<disk_name>/stop:
    post:
      summary: Stops all disks controller for disk
      parameters:
        - $ref: '#/components/parameters/DiskNameParam'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: string
        default:
          $ref: '#/components/responses/DefaultError'
  /disks/<disk_name>/start:
    post:
      summary: Trying to start all disk controllers for disk
      parameters:
        - $ref: '#/components/parameters/DiskNameParam'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: string
        default:
          $ref: '#/components/responses/DefaultError'
  /vdisks/<vdisk_id>/remount:
    post:
      summary: Remount partitions on vdisk
      parameters:
        - $ref: '#/components/parameters/VDiskIdParam'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: string
        default:
          $ref: '#/components/responses/DefaultError'
  /blobs/outdated:
    delete:
      summary: Close active blobs of holders not used recently
      operationId: finalizeOldBlobs
      responses: 
        '200':
          description: "Successfully finalized blobs"
        default:
          $ref: '#/components/responses/DefaultError'
  /alien:
    get:
      summary: Returns an alien dir info
      operationId: getAlien
      responses:
        '200':
          description: "A JSON array with alien Node names info"
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        default:
          $ref: '#/components/responses/DefaultError'
  /alien/dir:
    get:
      summary: Return directory of alien
      operationId: getAlienDir
      responses:
        '200': 
          description: "Directory"
          content:
            application/json:
              schema:
                ref: '#/components/schemas/Dir'
        default:
          $ref: '#/components/responses/DefaultError'
  /vdisks/<vdisk_id>/replicas/local/dirs:
    get:
      summary: Returns directories of local replicas of vdisk
      operationId: getReplicasLocalDirs
      responses:
        '200':
          description: "A JSON array with dirs"
          content:
            application/json:
              type: array
              items:
                ref: '#/components/schemas/Dir'
        default:
          $ref: '#/components/responses/DefaultError'
  /data/<key>:
    get:
      summary: Returns data by key
      operationId: getDataByKey
      parameters:
        - $ref: '#/components/parameters/DataKeyParam'
      responses:
        "200":
          description: "Binary data with inferred content type"
        default:
          $ref: "#/components/responses/DefaultError"
    post:
      summary: Add data to storage by key
      operationId: postDataByKey
      parameters:
        - $ref: '#/components/parameters/DataKeyParam'
      requestBody:
        description: Binary data
        required: true
      responses:
        "200":
          description: "Data successfully added"
        default:
          $ref: "#/components/responses/DefaultError"

components:
  responses:
    DefaultError:
      description: Unexpected error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
  parameters:
    DiskNameParam:
      name: DiskName
      in: path
      required: true
      schema:
        type: string
    VDiskIdParam:
      name: VDiskId
      in: path
      required: true
      schema:
        type: integer
    DataKeyParam:
      name: DataKey
      in: path
      required: true
      schema:
        type: string
  schemas:
    Node:
      properties:
        name:
          type: string
        address:
          type: string
        vdisks:
          type: string
          items:
            $ref: '#/components/schemas/VDisk'
      required:
        - name
        - address
    DiskState:
      properties:
        name:
          type: string
        path:
          type: string
        is_active:
          type: boolean
      required:
        - name
        - path
        - is_active
    VDisk:
      properties:
        id:
          type: integer
        replicas:
          type: array
          items:
            $ref: '#/components/schemas/Replica'
      required:
        - id
    Replica:
      properties:
        node:
          type: string
        disk:
          type: string
        path:
          type: string
      required:
        - type
        - disk
        - path
    VDiskPartitions:
      properties:
        vdisk:
          type: integer
        node:
          type: string
        disk:
          type: string
        partitions:
          type: array
          items:
            type: string
    Partition:
      properties:
        vdisk:
          type: integer
        node:
          type: string
        disk:
          type: string
        timestamp:
          type: integer
    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
      required:
        - code
        - message
    Dir:
      type: object
      properties:
        name:
          type: string
        path:
          type: string
        children:
          type: array
          items:
            $ref: '#/components/schemas/Dir'
    DistrFunc:
      type: object
      properties:
        func:
          type: string
          enum:
            - Mod
    Version:
      type: object
      properties:
        version:
          type: string
        build_time:
          type: string
    VersionInfo:
      type: object
      properties:
        bobversion:
          type:
            $ref: '#/components/schemas/Version'
        pearlversion:
          type:
            $ref: '#/components/schemas/Version'
