pub(crate) use super::prelude::*;

pub mod http;

/// Autogenerated code from proto
pub mod grpc {
    tonic::include_proto!("bob_storage");
}

pub mod prelude {
    pub(crate) use super::*;
    pub(crate) use rocket::{
        http::RawStr,
        http::Status,
        request::{FromParam, Request},
        response::{Responder, Response, Result as RocketResult},
        Config, Rocket, State,
    };
    pub(crate) use rocket_contrib::json::Json;
    pub(crate) use server::BobSrv;
}
