pub(crate) use super::prelude::*;

pub mod http;

/// Autogenerated code from proto
pub mod grpc {
    tonic::include_proto!("bob_storage");
}

pub mod prelude {
    pub(crate) use super::*;
    pub(crate) use {
        backend::Group as PearlGroup,
        rocket::{
            http::RawStr,
            http::Status,
            request::{FromParam, Request},
            response::{Responder, Response, Result as RocketResult},
            Config, Rocket, State,
        },
        rocket_contrib::json::Json,
        server::Server as BobServer,
    };
}
