[package]
name = "bob-grpc"
version = "1.6.0"
authors = ["Kirill Bushminkin <kb@qoollo.com>", "Pavel Iakushin <pyakushin@qoollo.com>"]
edition = "2018"

[dependencies]
http = "0.2.3"
log = "0.4"
prost = "0.7.0"
bytes = "1.0.1"
hyper = "0.14.2"
cfg-if = "1.0"
tonic = { version = "0.4.0", features = ["prost"] }
tower = "0.4.3"
tower-service = "0.3.0"
async-trait = "0.1"
lazy_static = "1.4.0"
#metrics = "0.12.1"

[dependencies.tokio]
version = "1.0.2"
features = ["full"]

[build-dependencies]
tonic-build = "0.4.0"

