[package]
name = "bob-backend"
version = "2.1.0-alpha.4"
authors = [
    "Kirill Bushminkin <kb@qoollo.com>",
    "Pavel Iakushin <pyakushin@qoollo.com>",
]
edition = "2018"

[dependencies]
anyhow = "1.0"
async-trait = "0.1"
bitflags = "1.3"
bob-common = { path = "../bob-common", features = [] }
bytes = "1.1"
cfg-if = "1.0"
chrono = "0.4"
coarsetime = "0.1.21"
futures = { version = "0.3", features = ["thread-pool"] }
http = "0.2"
humantime = "2.1"
hyper = { version = "0.14", default-features = false }
lazy_static = "1.4"
log = "0.4"
metrics = { version = "0.17", features = ["std"] }
mockall = "0.10"
parking_lot = "0.12.0"
prost = "0.9"
ring = "0.16"
serde = "1.0"
serde_derive = "1.0"
serde_yaml = "0.8"
stopwatch = "0.0.7"
thiserror = "1.0"
tonic = { version = "0.6", features = ["prost"] }
tower = "0.4"
tower-service = "0.3"

[dependencies.pearl]
version = "0.13.0"

[dependencies.tokio]
version = "1.14"
default-features = false
features = []

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "key_cmp_benchmark"
harness = false
