[package]
name = "bob-backend"
version = "1.6.1"
authors = [
    "Kirill Bushminkin <kb@qoollo.com>",
    "Pavel Iakushin <pyakushin@qoollo.com>",
]
edition = "2018"

[dependencies]

anyhow = "1.0.38"
async-trait = "0.1"
bitflags = "1.2.1"
bob-common = { path = "../bob-common" }
bytes = "1.0.1"
cfg-if = "1.0"
chrono = "0.4"
futures = { version = "0.3.12", features = ["thread-pool"] }
http = "0.2.3"
humantime = "2.1.0"
hyper = "0.14.2"
lazy_static = "1.4.0"
log = "0.4"
metrics = { version = "0.12.1", features = ["std"] }
mockall = "0.9.0"
prost = "0.7.0"
ring = "0.16.19"
serde = "1.0"
serde_derive = "1.0"
serde_yaml = "0.8"
stopwatch = "0.0.7"
thiserror = "1.0"
tonic = { version = "0.4.0", features = ["prost"] }
tower = "0.4.3"
tower-service = "0.3.0"

[dependencies.pearl]
#version = "=0.6.1"
git = "https://github.com/qoollo/pearl"
branch = "115-offloadable-bloom-filter"
#metrics = "0.12.1"

[dependencies.tokio]
version = "1.4"
features = ["full"]

[build-dependencies]
tonic-build = "0.4.0"
