name: build-docker-images

on:
  push:
    branches: [ 266-build-with-gitlab-actions ]
    tags:
      - '*'

jobs:

  build-docker-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checks-out repository 
        uses: actions/checkout@v2
      - name: Set env
        run: echo "VERSION=$(cat bob-apps/Cargo.toml | grep ^version | head -1 | awk '{print $3}' | sed -e 's/"//g' | sed -e 's/-/./g')" >> $GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push alpine image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: dockerfiles/alpine/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/bob:${{ env.VERSION }}-alpine3.12
      - name: Build and push ubuntu image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: dockerfiles/ubuntu/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/bob:${{ env.VERSION }}-ubuntu20.10