name: build-rpm

on:
  push:
    branches: [ 266-build-with-gitlab-actions ]
    tags:
      - '*'
    
jobs:

  build-release:
    runs-on: ubuntu-latest
    container: rust:1.53.0
    env:
      TARGET: "x86_64-unknown-linux-musl"
      BUILD_MODE: "release"
      RUST_TC_VER: nightly-2021-06-23
    steps:
      - name: Checks-out repository 
        uses: actions/checkout@v2
      - name: Building release
        run: |
          apt-get update && apt-get install -y --no-install-recommends musl-tools
          rustup install ${{ env.RUST_TC_VER }}
          rustup default ${{ env.RUST_TC_VER }}
          rustup target add ${{ env.TARGET }}
          cargo build --${{ env.BUILD_MODE }} --target=${{ env.TARGET }}  
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: bob-binaries
          path: |
            target/${{ env.TARGET }}/${{ env.BUILD_MODE }}/bobd
            target/${{ env.TARGET }}/${{ env.BUILD_MODE }}/bobp
            target/${{ env.TARGET }}/${{ env.BUILD_MODE }}/ccg
 
  build-rpm:
    runs-on: ubuntu-latest
    needs: build-release
    steps:
      - name: Checks-out repository 
        uses: actions/checkout@v2
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: bob-binaries
      - name: build rpm
        run: |
          VERSION=$(cat bob-apps/Cargo.toml | grep ^version | head -1 | awk '{print $3}' | sed -e 's/"//g' | sed -e 's/-/./g')
          echo Version:$VERSION
          sed -i "s/current_version/$VERSION/" bob.spec
          cur_dir_name=${PWD##*/}
          mkdir -p ./rpmbuild/{SOURCES,BUILD,RPMS,SPECS,SRPMS}
          tar czf ./rpmbuild/SOURCES/bob-${VERSION}.tar.gz --absolute-names ../${cur_dir_name}/target ../${cur_dir_name}/config-examples/{cluster,node,logger}.yaml ../${cur_dir_name}/bob.service --transform s/${cur_dir_name}/bob-${VERSION}/
          rpmbuild -ba --define "_topdir ${PWD}/rpmbuild" bob.spec