name: build

on:
  pull_request:
      types: [ opened, synchronize, reopened, ready_for_review, labeled, unlabeled ]
  push:
    branches: [ master, 276-tests-with-github-actions]
    
jobs:

  build:
    runs-on: ubuntu-latest
    env:
      TARGET: "x86_64-unknown-linux-musl"
      BUILD_MODE: "release"
    steps:
      - name: Checks-out repository 
        uses: actions/checkout@v2
      - name: Set env variable and install packages
        run: |
          export BOB_COMMIT_HASH=$(echo ${GITHUB_SHA} | cut -c1-8)
          apt-get update && apt-get install -y --no-install-recommends musl-tools
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      - name: Build release    
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --${{ env.BUILD_MODE }} --target=${{ env.TARGET }}    