name: build-docker-images

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-alpha.[0-9]+'
    branches: [ 298-build-bob-versions-with-8-byte-and-16-byte-keys ]

jobs:

  build-alpine-image:
    runs-on: ubuntu-latest
    environment: prod
    strategy:
      matrix:
        bob_key_size: [8, 16]
        include:
          - bob_key_size: 8
            image_tag_latest: ${{ secrets.DOCKERHUB_USERNAME }}/bob:latest
        include:
          - bob_key_size: 16
            image_name_postfix: -16KB
    steps:
      - name: Checks-out repository 
        uses: actions/checkout@v2
      - name: Set env
        run: |
          echo "VERSION=$(cat bob-apps/Cargo.toml | grep ^version | head -1 | awk '{print $3}' | sed -e 's/"//g' | sed -e 's/-/./g')" >> $GITHUB_ENV
          export BOB_COMMIT_HASH=$(echo ${GITHUB_SHA} | cut -c1-8)
          export BOB_KEY_SIZE=${{ matrix.bob_key_size }}
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/bob
          tags: |
            type=semver,pattern={{version}},suffix=-${{ matrix.bob_key_size }}B-alpine3.12
            type=semver,pattern={{version}},suffix=-${{ matrix.bob_key_size }}B
            type=semver,pattern={{version}},enable=${{ matrix.bob_key_size == 8 }}
            latest,enable=${{ matrix.bob_key_size == 8 }}
      - name: Build and push alpine image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: dockerfiles/alpine/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          build-args: |
            BOB_COMMIT_HASH=${BOB_COMMIT_HASH}
            BOB_KEY_SIZE=${BOB_KEY_SIZE}

  build-ubuntu-image:
    runs-on: ubuntu-latest
    environment: prod
    strategy:
      matrix:
        bob_key_size: [8, 16]
        include:
          - bob_key_size: 16
            image_name_postfix: -16KB
    steps:
      - name: Checks-out repository 
        uses: actions/checkout@v2
      - name: Set env
        run: |
          echo "VERSION=$(cat bob-apps/Cargo.toml | grep ^version | head -1 | awk '{print $3}' | sed -e 's/"//g' | sed -e 's/-/./g')" >> $GITHUB_ENV
          export BOB_COMMIT_HASH=$(echo ${GITHUB_SHA} | cut -c1-8)
          export BOB_KEY_SIZE=${{ matrix.bob_key_size }}
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push ubuntu image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: dockerfiles/ubuntu/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/bob:${{ env.VERSION }}${{ matrix.image_name_postfix }}-ubuntu20.10
          build-args: |
            BOB_COMMIT_HASH=${BOB_COMMIT_HASH}
            BOB_KEY_SIZE=${BOB_KEY_SIZE}