name: integration-tests
on:
  push:
    branches: [ "518-implement-semi-automatic-integration-tests" ]
  pull_request:
    branches: [ "518-implement-semi-automatic-integration-tests" ]

env:
  STORAGE_PATH: "/tmp"

jobs:
  deploy-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checks-out repo
        uses: actions/checkout@v2
      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install deps
        run: |
          /usr/bin/pip3 install -r ./requirements.txt
        working-directory: ./integration-tests
      - name: Install compose
        uses: KengoTODA/actions-setup-docker-compose@main
        with:
          version: '2.6.0'
      - name: Get version data
        run: |
          echo "VERSION=$(cat bob-apps/Cargo.toml | grep ^version | head -1 | awk '{print $3}' | sed -e 's/"//g' | sed -e 's/-/./g')" >> $GITHUB_ENV
      - name: Build tools
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --package=bob-apps --release
      - name: Generate config files for docker and bob
        env:
          AMOUNT_OF_NODES: "4"
        run: |
          ./generate_from_templates.py -a ${{ env.AMOUNT_OF_NODES }} -v qoollo/bob:${{ env.VERSION }} --path ${{ env.STORAGE_PATH }}
        working-directory: ./integration-tests
      - name: Deploy docker containers
        env:
          PATH_TO_CONFIGS: ${{ env.STORAGE_PATH }}/generated_configs
        run: |
          ./deploy.py --path ${{ env.PATH_TO_CONFIGS }} -d 4 -r 2
        working-directory: ./integration-tests
      - name: Run write/read tests
        env:
          PAYLOAD: "10240"
          COUNT: "10000"
        run: |
          ./tests.py -l ${{ env.PAYLOAD }} -c ${{ env.COUNT }} -n 0.0.0.0
        working-directory: ./integration-tests
