name: integration-tests
on:
  push:
    branches: [ "518-implement-semi-automatic-integration-tests" ]
  pull_request:
    branches: [ "518-implement-semi-automatic-integration-tests" ]

env:
  STORAGE_PATH: "/tmp"

jobs:
  deploy-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checks-out repo
        uses: actions/checkout@v2
      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install deps
        run: |
          pip3 install python-on-whales jinja2 docker
      - name: Install compose
        uses: KengoTODA/actions-setup-docker-compose@main
        with:
          version: '2.6.0'
        env:
          AMOUNT_OF_NODES: "4"
          VERSION: ${{ github.event.release.tag_name }}
      - name: Generate config files for docker and bob
        run: |
          ./generate_from_templates.py -a $AMOUNT_OF_NODES -v $VERSION --path $PATH
        working-directory: ./integration-tests
        env:
          PATH_TO_CONFIGS: $STORAGE_PATH/generated_configs
      - name: Deploy docker containers
        run: |
          ./deploy.py --path $PATH_TO_CONFIGS -d 4 -r 2
        working-directory: ./integration-tests
        env:
          PAYLOAD: "10240"
          COUNT: "10000"
      - name: Run write/read tests
        run: |
          ./tests.py -l $PAYLOAD -c $COUNT -n 0.0.0.0
        working-directory: ./integration-tests
