name: integration-tests
on:
  pull_request_review:
    types: [submitted]
    branches: [ "518-implement-semi-automatic-integration-tests" ]
  workflow_dispatch:
    inputs:
      bob_amount_of_nodes:
        description: 'Amount of nodes in bob cluster for tests'
        required: true
        default: '4'
      bob_disks:
        description: 'Vdisks count'
        required: true
        default: '4'
      bob_replicas:
        description: 'Amount of vdisks replicas'
        required: true
        default: '2'
      bob_payload:
        description: 'Payload size'
        required: true
        default: '10240'
      bob_count:
        description: 'Amount of records to process during test'
        required: true
        default: '10000'

jobs:
  build-binaries:
    if: github.event.review.state == 'approved'
    strategy:
      matrix:
        key: [8, 16]
    env:
      TARGET: "x86_64-unknown-linux-musl"
      BUILD_MODE: "release"
    runs-on: ubuntu-latest
    steps:
      - name: Checks-out repository 
        uses: actions/checkout@v2
      - name: Set env variables and install packages
        run: |
          echo "BOB_COMMIT_HASH=$(echo ${GITHUB_SHA} | cut -c1-8)" >> $GITHUB_ENV
          echo "BOB_KEY_SIZE=${{ matrix.key }}" >> $GITHUB_ENV
          sudo apt-get update && sudo apt-get install -y --no-install-recommends musl-tools
      - name: Install latest stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ env.TARGET }}
          default: true
      - name: Build binaries
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target=${{ env.TARGET }}
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: bob-binaries-${{ matrix.key }}
          path: |
            target/${{ env.TARGET }}/${{ env.BUILD_MODE }}/bobd
            target/${{ env.TARGET }}/${{ env.BUILD_MODE }}/bobp
            target/${{ env.TARGET }}/${{ env.BUILD_MODE }}/ccg
            target/${{ env.TARGET }}/${{ env.BUILD_MODE }}/brt
  build-docker-images:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        key: [8, 16]
    steps:
      - name: Checks-out repository 
        uses: actions/checkout@v2
      - name: Set env
        run: |
          echo "VERSION=$(cat bob-apps/Cargo.toml | grep ^version | head -1 | awk '{print $3}' | sed -e 's/"//g' | sed -e 's/-/./g')" >> $GITHUB_ENV
          echo "BOB_COMMIT_HASH=$(echo ${GITHUB_SHA} | cut -c1-8)" >> $GITHUB_ENV
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: qoollo/bob
          tags: |
            ${{ env.VERSION }}-key${{ matrix.key }}
      - name: Build image
        uses: docker/build-push-action@v2
        with:
          outputs: type=image,name=qoollo/bob:${{ env.VERSION }}-key${{ matrix.key }}
          context: .
          file: dockerfiles/alpine/Dockerfile
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            COMMIT_HASH=${{ env.BOB_COMMIT_HASH }}
            KEY_SIZE=${{ matrix.key}}
      - name: Save image
        run: |
          docker save -o /tmp/bob-images.tar qoollo/bob:${{ env.VERSION }}-key${{ matrix.key }}
        working-directory: ./integration-tests
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: bob-images
          path: |
            /tmp/bob-images.tar

  deploy-and-test:
    if: github.event.review.state == 'approved'
    needs: [build-binaries, build-docker-images]
    strategy:
      matrix:
        key: [8, 16]
    env:
      TARGET: "x86_64-unknown-linux-musl"
    runs-on: ubuntu-latest
    steps:
      - name: Checks-out repo
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Setup default variables for auto runs
        run: |
          INPUT=${{ github.event.inputs.bob_amount_of_nodes }}
          echo "BOB_AMOUNT_OF_NODES=${INPUT:-"4"}" >> $GITHUB_ENV
          INPUT=${{ github.event.inputs.bob_disks }}
          echo "BOB_DISKS=${INPUT:-"4"}" >> $GITHUB_ENV
          INPUT=${{ github.event.inputs.bob_replicas }}
          echo "BOB_REPLICAS=${INPUT:-"2"}" >> $GITHUB_ENV
          INPUT=${{ github.event.inputs.bob_payload }}
          echo "BOB_PAYLOAD=${INPUT:-"10240"}" >> $GITHUB_ENV
          INPUT=${{ github.event.inputs.bob_count }}
          echo "BOB_COUNT=${INPUT:-"10000"}" >> $GITHUB_ENV
      - name: Install deps
        run: |
          /usr/bin/pip3 install -r ./requirements.txt
        working-directory: ./integration-tests
      - name: Get version data
        run: |
          echo "VERSION=$(cat bob-apps/Cargo.toml | grep ^version | head -1 | awk '{print $3}' | sed -e 's/"//g' | sed -e 's/-/./g')" >> $GITHUB_ENV
          echo "VERSION_NO_FORMATTING=$(cat bob-apps/Cargo.toml | grep ^version | head -1 | awk '{print $3}' | sed -e 's/"//g')" >> $GITHUB_ENV
      - name: Download binaries
        uses: actions/download-artifact@v2
        with:
          name: bob-binaries-${{ matrix.key }}
          path: ./integration-tests
      - name: Download docker images
        uses: actions/download-artifact@v2
        with:
          name: bob-images
          path: ./integration-tests
      - name: Load docker images
        run: |
          docker load -i ./bob-images.tar
        working-directory: ./integration-tests
      - name: List availible images
        run: |
          docker image ls
      - name: Generate config files for docker and bob
        run: |
          ./generate_from_templates.py -a ${{ env.BOB_AMOUNT_OF_NODES }} -v qoollo/bob:${{ env.VERSION }}-key${{ matrix.key }} --path /tmp
        working-directory: ./integration-tests
      - name: Deploy docker containers
        run: |
          ./deploy.py --path ${{ env.BOB_STORAGE_PATH }}/generated_configs -d ${{ env.BOB_DISKS }} -r ${{ env.BOB_REPLICAS }}
        working-directory: ./integration-tests
      - name: Run write/read tests
        run: |
          ./tests.py -l ${{ env.BOB_PAYLOAD }} -c ${{ env.BOB_COUNT }} -n 0.0.0.0 -k ${{ matrix.key }}
        working-directory: ./integration-tests
