name: tests

on:
  pull_request:
      types: [ opened, synchronize, reopened, ready_for_review ]
  push:
    branches: [ master, 276-tests-with-github-actions]
    
jobs:

  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checks-out repository 
        uses: actions/checkout@v2
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          default: true
      - name: Tests
        run: |
          sudo apt-get update && apt-get install -y --no-install-recommends musl-tools
          cargo test