name: tests

on:
  pull_request:
      types: [ opened, synchronize, reopened, ready_for_review ]
  push:
    branches: [ master ]
    
jobs:

  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checks-out repository 
        uses: actions/checkout@v2
      - name: Install latest stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
      - name: Install packages
        run: sudo apt-get update && sudo apt-get install -y --no-install-recommends musl-tools
      - name: Tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --features testing